# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: run tests

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - name: Build
        run: |
          npm i
          npm run build
        env:
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          DB_URI: ${{ secrets.DB_URI }}
          SERVER: ${{ secrets.SERVER }}
          EMAIL: ${{ secrets.EMAIL }}
          EMAILPASSWORD: ${{ secrets.EMAILPASSWORD }}
          MAILLIST: ${{ secrets.MAILLIST }}
      - run: npm run test
